### ISSUE TITLE
Broken code for `DF_cloud_mesh_distance`

### ISSUE THREAD

**Issue by 9and3** [diffCheckOrg/diffCheck#123]
Hello @eleniv3d, my bad I let this slide and merge it but the file `code.py` in `DF_cloud_mesh_distance` seems to be broken.
In line 52-53 the `siffed_` variables are not created, apparently it is missing.

Here's now:
https://github.com/diffCheckOrg/diffCheck/blob/9734eea625995f1b73c36caca7368a7be84ef0c9/src/gh/components/DF_cloud_mesh_distance/code.py

And before:
https://github.com/diffCheckOrg/diffCheck/blob/1bd5727c761b0d395685dc48f3e923794e9fda35/src/gh/components/DF_cloud_mesh_distance/code.py

Do you what's the correct fix for the `siffed_` two variables now?

**Comment by eleniv3d** [comment]
it almost feels like it happened to me in a dream but I think it was left from an earlier idea of getting rid the Null pcd but we treat them differently. I got rid of the shift in the CVS exporter PR which is coming in 5'
