### ISSUE TITLE
pointcloud output of ghcomponents is a Systems.Collections.Generic.List

### ISSUE THREAD

**Issue by eleniv3d** [diffCheckOrg/diffCheck#26]
Tested on Rhino 8.7.24138.15431
![output](https://github.com/diffCheckOrg/diffCheck/assets/43600924/77ec470d-c308-4fde-a528-249bfb00b992)

**Comment by 9and3** [comment]
@eleniv3d I don't remember if we found a solution to this at one moment. Am I wrong?

**Comment by eleniv3d** [comment]
hey! it currently works for me. Not sure if it was updating Rhino again (now using 8.8 instead of 8.7) that did the trick but we can close the issue

**Comment by 9and3** [comment]
I updated to Rhino8.8 and it works indeed!
