### ISSUE TITLE
The legend scale is not showing lower decimals

### ISSUE THREAD

**Issue by 9and3** [diffCheckOrg/diffCheck#84]
Since I am evaluating elements in the order of millimeters but working in a Rhino meter environment for better convenience of all the backend functions. Unfortunatelly to see the real difference under 1cm is difficult since the values are truncated in the viz component:

![image](https://github.com/user-attachments/assets/d12b9c9d-2cef-45f6-b4d5-3be05e9672b3)

**Comment by DamienGilliard** [comment]
same 

![image](https://github.com/user-attachments/assets/7ac0008e-1f54-4f5b-9c6a-31a9680f17bc)
