### ISSUE TITLE
per-face metric when analysing the joints

### ISSUE THREAD

**Issue by DamienGilliard** [diffCheckOrg/diffCheck#89]
It would be great to have a per-face rmse, or another metric, to objectivize the quality of the joints. For now we only have a value for the whole joint.

For example, we would get 3 values for this joint: 
![image](https://github.com/user-attachments/assets/05990a11-f069-4265-8856-42e7f367dfad)

**Comment by 9and3** [comment]
It might require a PR with some coordination and co-contribution for this one @eleniv3d / @DamienGilliard.
